wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    code_path: code/examples/run_expt.py
    framework: huggingface
    huggingface_version: 4.3.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      - 5
      - 11
      4: 3.8.5
      5: 0.10.22
      6: 4.3.2
      8:
      - 5
algo_log_metric:
  desc: null
  value: accuracy
algorithm:
  desc: null
  value: KLaDRO
batch_size:
  desc: null
  value: 16
coral_penalty_weight:
  desc: null
  value: 10.0
dataset:
  desc: null
  value: civilcomments
dataset_kwargs:
  desc: null
  value: {}
device:
  desc: null
  value: cuda:0
distinct_groups:
  desc: null
  value: true
download:
  desc: null
  value: false
eval_epoch:
  desc: null
  value: null
eval_loader:
  desc: null
  value: standard
eval_only:
  desc: null
  value: false
eval_splits:
  desc: null
  value: []
eval_transform:
  desc: null
  value: bert
evaluate_all_splits:
  desc: null
  value: true
frac:
  desc: null
  value: 1.0
group_dro_step_size:
  desc: null
  value: 0.01
groupby_fields:
  desc: null
  value:
  - black
  - y
irm_lambda:
  desc: null
  value: 1.0
irm_penalty_anneal_iters:
  desc: null
  value: null
loader_kwargs:
  desc: null
  value:
    num_workers: 1
    pin_memory: true
log_dir:
  desc: null
  value: /data/wilds/log/civilcomments_KLaDRO
log_every:
  desc: null
  value: 50
loss_function:
  desc: null
  value: cross_entropy
lr:
  desc: null
  value: 1.0e-05
max_grad_norm:
  desc: null
  value: 1.0
max_token_length:
  desc: null
  value: 300
model:
  desc: null
  value: distilbert-base-uncased
model_kwargs:
  desc: null
  value: {}
n_epochs:
  desc: null
  value: 5
n_groups_per_batch:
  desc: null
  value: 4
no_group_logging:
  desc: null
  value: false
optimizer:
  desc: null
  value: AdamW
optimizer_kwargs:
  desc: null
  value: {}
process_outputs_function:
  desc: null
  value: multiclass_logits_to_pred
progress_bar:
  desc: null
  value: false
resize_scale:
  desc: null
  value: null
resume:
  desc: null
  value: false
root_dir:
  desc: null
  value: /data/wilds/data
save_best:
  desc: null
  value: true
save_last:
  desc: null
  value: true
save_pred:
  desc: null
  value: true
save_step:
  desc: null
  value: null
scheduler:
  desc: null
  value: linear_schedule_with_warmup
scheduler_kwargs:
  desc: null
  value:
    num_warmup_steps: 0
scheduler_metric_name:
  desc: null
  value: null
scheduler_metric_split:
  desc: null
  value: val
seed:
  desc: null
  value: 0
split_scheme:
  desc: null
  value: official
target_resolution:
  desc: null
  value: null
train_loader:
  desc: null
  value: group
train_transform:
  desc: null
  value: bert
uniform_over_groups:
  desc: null
  value: true
use_wandb:
  desc: null
  value: true
val_metric:
  desc: null
  value: acc_wg
val_metric_decreasing:
  desc: null
  value: false
version:
  desc: null
  value: null
weight_decay:
  desc: null
  value: 0.01
