wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    code_path: code/examples/run_expt.py
    framework: huggingface
    huggingface_version: 4.3.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      - 5
      - 11
      4: 3.8.5
      5: 0.10.22
      6: 4.3.2
      8:
      - 5
algo_log_metric:
  desc: null
  value: accuracy
algorithm:
  desc: null
  value: deepCORAL
batch_size:
  desc: null
  value: 32
coral_penalty_weight:
  desc: null
  value: 0.1
dataset:
  desc: null
  value: camelyon17
dataset_kwargs:
  desc: null
  value: {}
device:
  desc: null
  value: cuda:1
distinct_groups:
  desc: null
  value: true
download:
  desc: null
  value: false
eval_epoch:
  desc: null
  value: null
eval_loader:
  desc: null
  value: standard
eval_only:
  desc: null
  value: false
eval_splits:
  desc: null
  value: []
eval_transform:
  desc: null
  value: image_base
evaluate_all_splits:
  desc: null
  value: true
frac:
  desc: null
  value: 1.0
group_dro_step_size:
  desc: null
  value: null
groupby_fields:
  desc: null
  value:
  - hospital
irm_lambda:
  desc: null
  value: 1.0
irm_penalty_anneal_iters:
  desc: null
  value: null
loader_kwargs:
  desc: null
  value:
    num_workers: 4
    pin_memory: true
log_dir:
  desc: null
  value: /data/wilds/log/camelyon17_deepCORAL
log_every:
  desc: null
  value: 50
loss_function:
  desc: null
  value: cross_entropy
lr:
  desc: null
  value: 0.001
max_grad_norm:
  desc: null
  value: null
max_token_length:
  desc: null
  value: null
model:
  desc: null
  value: densenet121
model_kwargs:
  desc: null
  value:
    pretrained: false
n_epochs:
  desc: null
  value: 5
n_groups_per_batch:
  desc: null
  value: 2
no_group_logging:
  desc: null
  value: false
optimizer:
  desc: null
  value: SGD
optimizer_kwargs:
  desc: null
  value:
    momentum: 0.9
process_outputs_function:
  desc: null
  value: multiclass_logits_to_pred
progress_bar:
  desc: null
  value: false
resize_scale:
  desc: null
  value: null
resume:
  desc: null
  value: false
root_dir:
  desc: null
  value: /data/wilds/data
save_best:
  desc: null
  value: true
save_last:
  desc: null
  value: true
save_pred:
  desc: null
  value: true
save_step:
  desc: null
  value: null
scheduler:
  desc: null
  value: null
scheduler_kwargs:
  desc: null
  value: {}
scheduler_metric_name:
  desc: null
  value: null
scheduler_metric_split:
  desc: null
  value: val
seed:
  desc: null
  value: 0
split_scheme:
  desc: null
  value: official
target_resolution:
  desc: null
  value:
  - 96
  - 96
train_loader:
  desc: null
  value: group
train_transform:
  desc: null
  value: image_base
uniform_over_groups:
  desc: null
  value: true
use_wandb:
  desc: null
  value: true
val_metric:
  desc: null
  value: acc_avg
val_metric_decreasing:
  desc: null
  value: false
version:
  desc: null
  value: null
weight_decay:
  desc: null
  value: 0.01
